spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/byun/h2/dbfile/h2_214/project/middle/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  messages:
    basename: messages,errors

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.trace: trace
    org.hibernate.type.descriptor.sql: trace